export const STYLES = `
.dph-seat{display:inline-flex;align-items:center;gap:4px;max-width:min(100%,240px);min-height:28px;padding:0 8px;border:0;border-radius:16px;background:transparent;color:var(--dsw-alias-label-primary);font-family:inherit;font-size:13px;font-weight:500;line-height:20px;white-space:nowrap;overflow:hidden;cursor:pointer}
.dph-seat:not(:disabled):hover,.dph-seat[aria-expanded=true]{background:var(--dsw-alias-interactive-bg-hover)}
.dph-seat:disabled{cursor:default;color:var(--dsw-alias-label-quaternary)}
.dph-seat svg{flex:none}.dph-seat__icon{color:var(--dsw-alias-label-primary)}.dph-seat__label{overflow:hidden;text-overflow:ellipsis}.dph-seat__chevron{color:var(--dsw-alias-label-caption)}
.dph-menu-item{display:flex;flex-direction:column;gap:2px;max-width:280px}.dph-menu-item__name{font-size:13px;line-height:20px;color:var(--dsw-alias-label-primary)}.dph-menu-item__desc{font-size:12px;line-height:16px;color:var(--dsw-alias-label-caption);white-space:normal}
.dph-sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0}.dph-section{display:flex;flex-direction:column;gap:18px;max-width:760px;color:var(--dsw-alias-label-primary)}
.dph-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.dph-title{margin:0;font-size:18px;line-height:1.4;font-weight:600;letter-spacing:0}.dph-intro{max-width:600px;margin:5px 0 0;color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:1.6}.dph-summary{flex:none;padding-top:3px;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:20px;font-variant-numeric:tabular-nums}
.dph-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.dph-search{position:relative;display:flex;align-items:center;flex:1 1 240px;min-width:180px;max-width:360px}.dph-search svg{position:absolute;left:10px;color:var(--dsw-alias-label-caption);pointer-events:none}.dph-search input{box-sizing:border-box;width:100%;height:34px;padding:0 10px 0 34px;border:1px solid var(--dsw-alias-border-l3);border-radius:7px;background:transparent;color:var(--dsw-alias-label-primary);font-family:inherit;font-size:13px;line-height:20px;outline:0}.dph-search input::placeholder{color:var(--dsw-alias-label-caption)}.dph-search input:focus{border-color:var(--dsw-alias-brand-primary)}
.dph-segments{display:inline-flex;align-items:center;padding:2px;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;background:var(--dsw-alias-bg-module-platform)}.dph-segments button{height:28px;padding:0 10px;border:0;border-radius:5px;background:transparent;color:var(--dsw-alias-label-tertiary);font-family:inherit;font-size:12px;font-weight:500;line-height:20px;cursor:pointer}.dph-segments button[aria-pressed=true]{background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-primary);box-shadow:0 1px 2px var(--dsw-alias-border-l2)}.dph-segments button:focus-visible,.dph-reset:focus-visible,.dph-icon-button:focus-visible,.dph-switch:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
.dph-toolbar__actions{display:flex;align-items:center;gap:8px;margin-left:auto;flex-wrap:wrap}.dph-reset{display:inline-flex;align-items:center;gap:6px;height:32px;padding:0 10px;border:1px solid var(--dsw-alias-border-l3);border-radius:7px;background:transparent;color:var(--dsw-alias-label-secondary);font-family:inherit;font-size:12px;font-weight:500;line-height:20px;cursor:pointer}.dph-reset:not(:disabled):hover{background:var(--dsw-alias-interactive-bg-hover)}.dph-reset:disabled{opacity:.45;cursor:default}
.dph-notice,.dph-error,.dph-empty{margin:0;padding:10px 12px;border-radius:7px;font-size:12px;line-height:1.55}.dph-notice{border:1px solid var(--dsw-alias-state-warn-secondary);background:var(--dsw-alias-state-warn-tertiary);color:var(--dsw-alias-state-warn-label)}.dph-error{border:1px solid var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-state-error-primary)}.dph-error button{margin-left:10px;border:0;background:transparent;color:inherit;text-decoration:underline;cursor:pointer}.dph-empty{color:var(--dsw-alias-label-tertiary);background:var(--dsw-alias-bg-module-platform)}
.dph-groups{display:flex;flex-direction:column;gap:26px}.dph-group{display:flex;flex-direction:column;gap:8px}.dph-group__head{display:flex;align-items:center;gap:8px;margin:0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:20px;font-weight:600;letter-spacing:0;text-transform:uppercase}.dph-group__count{min-width:20px;padding:0 6px;border-radius:9px;background:var(--dsw-alias-bg-module-platform);font-size:11px;text-align:center;font-variant-numeric:tabular-nums}.dph-list{list-style:none;margin:0;padding:0;border-top:1px solid var(--dsw-alias-border-l2)}
.dph-row{display:flex;align-items:center;gap:20px;min-height:70px;padding:10px 4px;border-bottom:1px solid var(--dsw-alias-border-l2)}.dph-row[data-hidden=true] .dph-row__copy{opacity:.58}.dph-row__copy{flex:1;min-width:0;transition:opacity 120ms ease}.dph-row__top{display:flex;align-items:center;gap:7px;min-width:0;flex-wrap:wrap}.dph-row__name{flex:0 1 auto;min-width:0;max-width:100%;overflow:hidden;text-overflow:ellipsis;color:var(--dsw-alias-label-primary);font-size:14px;line-height:20px;font-weight:600;white-space:nowrap}.dph-badge{flex:none;padding:1px 6px;border:1px solid var(--dsw-alias-border-l3);border-radius:8px;color:var(--dsw-alias-label-tertiary);font-size:10px;line-height:15px;font-weight:500}.dph-badge--error{border-color:var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-state-error-primary)}.dph-row__desc{display:block;margin-top:3px;overflow:hidden;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px;text-overflow:ellipsis;white-space:nowrap}.dph-row__id{display:block;margin-top:2px;overflow:hidden;color:var(--dsw-alias-label-caption);font:11px/16px var(--dsw-font-mono,ui-monospace,SFMono-Regular,Menlo,monospace);text-overflow:ellipsis;white-space:nowrap}.dph-row__control{display:flex;align-items:center;gap:10px;flex:none}.dph-order-actions{display:flex;align-items:center;gap:2px}.dph-icon-button{display:inline-grid;place-items:center;width:28px;height:28px;padding:0;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-tertiary);cursor:pointer}.dph-icon-button:not(:disabled):hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dph-icon-button:disabled{opacity:.3;cursor:default}.dph-row__state{width:38px;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:18px;text-align:right}
.dph-switch{box-sizing:border-box;position:relative;width:36px;height:20px;padding:2px;border:0;border-radius:10px;background:var(--dsw-alias-border-l3);cursor:pointer;transition:background 120ms ease}.dph-switch[aria-checked=true]{background:var(--dsw-alias-brand-primary)}.dph-switch__thumb{display:block;width:16px;height:16px;border-radius:50%;background:var(--dsw-alias-label-primary-foreground);transition:transform 120ms ease}.dph-switch[aria-checked=true] .dph-switch__thumb{transform:translateX(16px)}
@media(max-width:620px){.dph-heading{display:block}.dph-summary{padding-top:8px}.dph-toolbar__actions{margin-left:0}.dph-toolbar{align-items:stretch}.dph-search{max-width:none;flex-basis:100%}.dph-row{gap:12px}.dph-row__state{display:none}.dph-row__desc{white-space:normal;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2}}@media(max-width:440px){.dph-row{align-items:flex-start;flex-wrap:wrap}.dph-row__control{width:100%;justify-content:flex-end}}
@media(prefers-reduced-motion:reduce){.dph-row__copy,.dph-switch,.dph-switch__thumb{transition:none}}
`
